### PR TITLE
Process only container metrics from the event stream, filter space and org, address some checkstyle issues

### PR DESCRIPTION
**Pull request by bandesz**
Changes:
 * Process only container metrics from the event stream
 * Add filter for space and organisation
 * Address some checkstyle issues

Todo:
 - [ ] add tests

### CODE REVIEW

**Comment by dcarley** [comment]
Thanks @bandesz!

Would you be able to split each logical change out to a separate commit and describe the rationale for the change in the commit message? It would make it much easier for someone from our team to review the PR. 

For example:

- the stylistic changes look good and uncontroversial, so it'd be good to look over them in a single commit and then concentrate on the other functional changes in separate commits
- why is filtering by org and space useful? was there a problem using role assignment to achieve the same effect?
- what is the effect of filtering the event type early? does it improve performance, or reduce errors, or is it just "cleaner"?

**Comment by bandesz** [comment]
@dcarley 

I splitted the commits as you requested.

The app should only process container metrics, because currently it was creating empty metrics even for log events (which seems like a bug). Or maybe I missed it that we filter these events in any other way?

As the app runs in a specific space it makes more sense to run a separate metrics collector in every space. At the moment we don't have a separate user for every space. Also I was thinking that if this app runs e.g. in the production space logically it should only collect metrics from production. But now I'm thinking maybe we should create just a separate space from preview/staging/prod and run it from there.

**Comment by dcarley** [comment]
> I splitted the commits as you requested.

Thanks! Would you be able to add some rationale to the commit messages too? It'll help us to understand the changes when reviewing now, and when maintaining the code in future.

> The app should only process container metrics, because currently it was creating empty metrics even for log events (which seems like a bug). Or maybe I missed it that we filter these events in any other way?

Yep, that's a bug 👍  They used to be filtered by the thing that processes the metrics which we removed in 7286686c4ff42b1a1d2d853a42e03902188b4e03. Agree that it makes sense to not even send them down a channel if we don't support them.

> As the app runs in a specific space it makes more sense to run a separate metrics collector in every space. At the moment we don't have a separate user for every space. Also I was thinking that if this app runs e.g. in the production space logically it should only collect metrics from production. But now I'm thinking maybe we should create just a separate space from preview/staging/prod and run it from there.

Our original thinking was that it would be more efficient to run one copy of the app which would monitor all spaces. You can use the least-privileged ["Space Auditor"](https://docs.cloudfoundry.org/concepts/roles.html#roles) role for each space, so there shouldn't be a risk of mixing production and non-production usage. You description of running it in a separate "monitoring" space makes sense.

**Comment by dcarley** [comment]
This has been superseded by #7.

**Pull request closed without merging**
